export const STORY_BOOK = {
  INPUTS: {
    AUTOCOMPLETE: 'AUTOCOMPLETE',
    BUTTON: 'BUTTON',
    GROUP: 'GROUP',
    CHECKBOX: 'CHECKBOX',
    FLOATING_ACTION_BUTTON: 'FLOATING_ACTION_BUTTON',
    RADIO_GROUP: 'RADIO_GROUP',
    RATING: 'RATING',
    SELECT: 'SELECT',
    SLIDER: 'SLIDER',
    SWITCH: 'SWITCH',
    TEXT_FIELD: 'TEXT_FIELD',
    TRANSFER_LIST: 'TRANSFER_LIST',
    TOGGLE_BUTTON: 'TOGGLE_BUTTON',
  },
};
